image: hub500/amaxwebide:0.0.5

ports:
- port: 3000
  onOpen: ignore
- port: 8000
  onOpen: ignore
- port: 8080
  onOpen: ignore
- port: 8888
  onOpen: ignore
- port: 9876
  onOpen: ignore

tasks:
- before: cd webapp
  init: yarn
  command: nginx -c $PWD/nginx.conf; npx webpack-dev-server

- name: amnod runing
  before: amcli wallet unlock --password </password
  init: amnod --config-dir ~/eosio/chain/config --data-dir ~/eosio/chain/data -e -p amax --plugin eosio::chain_api_plugin --contracts-console
  command: |
    amcli create account amax amax.token AM6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV -p amax@active
    cd /home/gitpod/contracts
    amcli set code amax.token amax.token.wasm -p amax.token@active
    amcli set abi amax.token amax.token.abi -p amax.token@active
    amcli push action amax.token create '["amax","1000000000.00000000 AMAX"]' -p amax.token@active
    amcli push action amax.token issue '["amax","1000000000.00000000 AMAX","amax issue"]' -p amax@active

# 没有部署成功
# - name: deploy-amax-token
#   before: cd /home/gitpod/contracts
#   init: gp sync-await bundle
#   command: |
#     amcli create account amax amax.token AM6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV -p amax@active
#     amcli set code amax.token amax.token.wasm -p amax.token@active
#     amcli set abi amax.token amax.token.abi -p amax.token@active
#     amcli push action amax.token create '["amax","1000000000.00000000 AMAX"]' -p amax.token@active
#     amcli push action amax.token issue '["amax","1000000000.00000000 AMAX","amax issue"]' -p amax@active
